frontend-build:
	./gradlew :contacts-frontend:exportJavascriptProduction
	docker compose build frontend
	# Remove intermediate images (<none>) generated by the build
	docker image prune -f

contact-build:
	docker compose build contact
	docker image prune -f

icon-handling-build:
	mkdir -p contacts-backend/icons
	docker compose build icon-handling
	docker image prune -f

backend-build: contact-build icon-handling-build
	docker compose build db nginx
	docker image prune -f

build: frontend-build backend-build

up:
	docker compose up