services:

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - contact
      - icon-handling
    networks:
      - backend

  db:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_DATABASE: contacts
      MARIADB_USER: user
      MARIADB_PASSWORD: userpassword
      MARIADB_ROOT_PASSWORD: rootpassword
    networks:
      - backend
    volumes:
      - ./db_data:/var/lib/mysql
#    env_file:
#      - .env
    ports:
      - "3306:3306"

  contact:
    build:
      context: .
      dockerfile: contact/Dockerfile
    image: contact
    depends_on:
      - db
#    volumes:
#      - ./contact/target:/usr/src/myapp
#    command:
#      - bash -c "cd /usr/src/myapp && java -jar contacts${JAR_NAME} #check for ./contacts.jar
    env_file:
      - .env
    networks:
      - backend

  icon-handling:
    build:
      context: .
      dockerfile: icon-handling/Dockerfile
    image: icon-handling
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./icons:/app/icons

networks:
  backend:
    driver: bridge
