spring:
  application:
    name: Contacts

  datasource:
    url: jdbc:mariadb://${MYSQL_HOST}:${MYSQL_PORT}/contacts
    username: user
    password: userpassword
    driver-class-name: org.mariadb.jdbc.Driver
  profiles:
    active: default

  jpa:
    hibernate:
      ddl-auto: update  # or validate/create-drop/etc.
#      dll-auto=create-drop
    show-sql: true
  web:
    resources:
      add-mappings: false

shared:
  hostIconHandling: ${ICON_HANDLING_HOST}:${BE_PORT}
  apiIconHandling: ${BE_API}

server:
  port: ${BE_PORT}
  servlet:
    context-path: ${BE_API}