shared:
  hostContact: ${CONTACT_HOST}:${BE_PORT}
  apiContact: ${BE_API}

spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  application:
    name: Icon Handling
  profiles:
    active: default

server:
  port: ${BE_PORT}
  servlet:
    context-path: ${BE_API}

iconhandling:
  iconsDirectory: icons