server:
  port: 8092
  servlet:
    context-path: /api/icon-handling/v1
shared:
  contactApi: /api/contact/v1
  contactHost: http://localhost:8091

iconhandling:
  iconsDirectory: contacts-backend/icon-handling/icons