events { }

http {
    upstream contact {
        server contact:8080;
    }

    upstream icon-handling {
        server icon-handling:8080;
    }

    server {
        listen 80;

        # Contact service
        location /api/contact/v1/ {
            proxy_pass http://contact/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
        }

        location /api/icon-handling/v1/ {
            proxy_pass http://icon-handling/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            client_max_body_size 20M;
        }

    }
}
